site_name: mSCAPE
site_url: https://climb-tre.github.io/mSCAPE/
site_author: CLIMB-TRE

theme:
  name: material
  font:
    text: IBM Plex Sans
  palette:
    primary: black
    accent: indigo
    # # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: black
    #   accent: black
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   accent: black
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
      
  features:
    # - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.top
    - toc.integrate
    - content.code.copy

extra:
  generator: false

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
